on:
  push:
    branches:
      - main

env:

  DOCKERHUB_NAMESPACE: c0750688
  DOCKERHUB_REPOSITORY: flashcard-app
  DOCKERHUB_TEST_REPOSITORY: flashcard-app-test
  IMAGE_VERSION: v1.0.0

jobs:

  build-docker-image:
    name: Build Docker Image
    environment: development
    runs-on: EC2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Builder Docker Main Image
        run: docker build -t $DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:$IMAGE_VERSION -f docker/Dockerfile .
      - name: Push Docker Main Image
        run: docker push $DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:$IMAGE_VERSION
      - name: Build Test Docker Image
        run: |
          mv .dockerignore .dockerignore.temp
          docker build -t $DOCKERHUB_NAMESPACE/$DOCKERHUB_TEST_REPOSITORY:$IMAGE_VERSION -f docker/DockerfileTest .
          mv .dockerignore.temp .dockerignore
      - name: Push Test Docker Image
        run: docker push $DOCKERHUB_NAMESPACE/$DOCKERHUB_TEST_REPOSITORY:$IMAGE_VERSION

  unittest:
    name: Unit Testing
    needs: [build-docker-image]
    environment: development
    runs-on: EC2
    steps:
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pull Test Docker Image
        run: docker pull $DOCKERHUB_NAMESPACE/$DOCKERHUB_TEST_REPOSITORY:$IMAGE_VERSION
      - name: Run Test Docker Image
        run: |
          docker run --rm \
            -e MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }} \
            -e MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} \
            $DOCKERHUB_NAMESPACE/$DOCKERHUB_TEST_REPOSITORY:$IMAGE_VERSION

  deploy-docker-image:
    name: Deploy the image
    needs: [unittest, build-docker-image]
    runs-on: EC2
    steps:
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pull Image
        run: |
          docker pull $DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:$IMAGE_VERSIO
      - name: Deploy Image
        run: |
          docker rm -f $DOCKERHUB_REPOSITORY || true
          docker run -d -p 5000:5000 --name $DOCKERHUB_REPOSITORY -e MONGODB_USERNAME=${{ secrets.MONGODB_USERNAME }} -e MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }} $DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:$IMAGE_VERSION